version: "3.3"

networks:
  config_qmediator:
    external: true


services:
  course-recommender:
    hostname: ${RECOMMENDER_HOSTNAME}
    container_name: ${RECOMMENDER_HOSTNAME}
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      # APP ENV Vars
      PROD_STATUS: ${PROD_STATUS}

      # PostgreSQL ENV Vars
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

      # Qualichain DB ENV VARS
      QUALICHAIN_DB_HOST: ${QUALICHAIN_DB_HOST}
      QUALICHAIN_DB_PORT: ${QUALICHAIN_DB_PORT}

      # AnalEyeZer ENV Vars
      ANALEYEZER_HOST: ${ANALEYEZER_HOST}
      ANALEYEZER_PORT: ${ANALEYEZER_PORT}

    ports:
      - ${API_PORT}:5000
    networks:
      - config_qmediator
